### ISSUE TITLE
Undetected or not ?

### ISSUE THREAD

**Issue by neazen** [alxbrn/r6s-external-nuklear-hook#1]
Is this still undetected ? cause the thread on unknow has been made the 17th september and idk if it is or not (still going to use it with an hwid spoofer but I was wondering)

**Comment by alxbrn** [comment]
Yes it is undetected.

**Comment by neazen** [comment]
oh and possible to get an compiled version of the r6s external (got the kdmapper) my vs2019 cant find WDK, I installed it to vs but it doesnt seem to work (it says WindowsKernelModeDriver10.0 (not installed) but I have it installed)

**Comment by alxbrn** [comment]
You need to install WDK on your system, and I don't provide compiled binaries you need to compile it on your own. [wdk download link for 1903](https://go.microsoft.com/fwlink/?linkid=2085767)

**Comment by neazen** [comment]
Yeah I already launched the setup and downloaded it but what do I do after ?
