### ISSUE TITLE
All of this is stolen from Frankoo

### ISSUE THREAD

**Issue by IChooseYou** [alxbrn/r6s-external-nuklear-hook#2]
Why release code that you didn't write?

**Comment by not-frankoo** [comment]
literally took everything without even trying to change something this is a leak! who gave it to you from the first place?

**Comment by PeripheralVisionPD2** [comment]
he had to release this knowing it was someone elses code

**Comment by Nader-Sl** [comment]
what's the point of doing this other than disrespect and probably some enemies?

**Comment by r1cky33** [comment]
gamehacking is just putting a puzzle together^^ truely someone elses code

**Comment by Object9999** [comment]
Source stolen from Frankoo

**Comment by 1ntrusion** [comment]
The project originally belongs to from Frankoo.

**Comment by odiahDIgAUYdgawYUCdgayuGDuyawGDywa** [comment]
![](https://cdn.discordapp.com/attachments/613422962955255811/630602546645434378/72221964_937573029955852_6546360151523105197_n.mp4)

this is not epic

**Comment by odiahDIgAUYdgawYUCdgayuGDuyawGDywa** [comment]
https://cdn.discordapp.com/attachments/613422962955255811/630631507765231641/71485589_138461250754232_6786116886539352812_n.mp4

**Comment by odiahDIgAUYdgawYUCdgayuGDuyawGDywa** [comment]
https://cdn.discordapp.com/attachments/617761611666423839/630633846391439372/maxresdefault.png

**Comment by odiahDIgAUYdgawYUCdgayuGDuyawGDywa** [comment]
https://cdn.discordapp.com/attachments/613422962955255811/630635282026463242/72614028_2388508264603216_3853987572035213666_n.mp4

**Comment by odiahDIgAUYdgawYUCdgayuGDuyawGDywa** [comment]
https://cdn.discordapp.com/attachments/613422962955255811/630635299680157706/66462419_139042357294579_4953821932691042957_n.mp4

**Comment by odiahDIgAUYdgawYUCdgayuGDuyawGDywa** [comment]
https://cdn.discordapp.com/attachments/613422962955255811/630636140491440128/49994984_2352176784855492_7303292735429806069_n.mp4

**Comment by odiahDIgAUYdgawYUCdgayuGDuyawGDywa** [comment]
https://cdn.discordapp.com/attachments/613422962955255811/630636157172056067/47487831_210112053210321_2407606305376196272_n.mp4

**Comment by odiahDIgAUYdgawYUCdgayuGDuyawGDywa** [comment]
https://cdn.discordapp.com/attachments/613422962955255811/630636639604965406/45824257_294099687980025_6175936682643605472_n.mp4

**Comment by alxbrn** [comment]
I got the source from some random and had no use for it, so someone else might have joy from it. I don't get why people get butt hurt over releasing sources, let everyone have fun instead of keeping shit private.

**Comment by Nader-Sl** [comment]
let everyone have fun, ok can we have orgy with your sister/mom?
